[package]
name = "call23re/soma"
description = "A compositional input library."
version = "0.1.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/call23re/soma"
include = ["src", "src/**", "wally.toml", "default.project.json", "LICENSE"]
exclude = ["**"]
realm = "shared"